version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_USER: "john"
      MYSQL_PASSWORD: "1234"
      MYSQL_DATABASE: "sym"
    volumes:
      - ./docker/mysql/db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
